services:
  turtlebot-vis:
    #restart: always
    build:
      context: ./
      dockerfile: docker_vis/Dockerfile
      # args:
      #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      #   - CYCLONEDDS_URI=file:///root/turtlebot3_ws/cylconedds_config.xml
    image: nobel86/turtlebot-rpi5-vis:latest
    stdin_open: true
    network_mode: host
    tty: true  
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTH}
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///root/turtlebot3_ws/cylconedds_config.xml
    container_name: turtlebot-vis
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash 

